### ISSUE TITLE
Исследовать sitemap.xml и выделить бизнес-сущности для создания в БД

### ISSUE THREAD

**Issue by gamefreakru** [epitaphprince/cesp-database#2]
Во вложении будет файл sitemap.xml. 
Нужно понять какие сущности нужно часто менять и обновлять и они требуют добавления их БД.

<url>
  <loc>http://centroespanol.ru/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/curs</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas</loc>
</url>
<url>
  <loc>http://centroespanol.ru/blog</loc>
</url>
<url>
  <loc>http://centroespanol.ru/contact</loc>
</url>
<url>
  <loc>http://centroespanol.ru/about</loc>
</url>
<url>
  <loc>http://centroespanol.ru/news</loc>
</url>
<url>
  <loc>http://centroespanol.ru/meropriyatia</loc>
</url>
<url>
  <loc>http://centroespanol.ru/pressa</loc>
</url>
<url>
  <loc>http://centroespanol.ru/where</loc>
</url>
<url>
  <loc>http://centroespanol.ru/test</loc>
</url>
<url>
  <loc>http://centroespanol.ru/matricula</loc>
</url>
<url>
  <loc>http://centroespanol.ru/ispanskij-dlya-nachinayushchix</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Institut_teatra_barcelona</loc>
</url>
<url>
  <loc>http://centroespanol.ru/salsa</loc>
</url>
<url>
  <loc>http://centroespanol.ru/conversacion</loc>
</url>
<url>
  <loc>http://centroespanol.ru/catala</loc>
</url>
<url>
  <loc>http://centroespanol.ru/horario</loc>
</url>
<url>
  <loc>http://centroespanol.ru/verano</loc>
</url>
<url>
  <loc>http://centroespanol.ru/nivel</loc>
</url>
<url>
  <loc>http://centroespanol.ru/dele</loc>
</url>
<url>
  <loc>http://centroespanol.ru/matriculacine</loc>
</url>
<url>
  <loc>http://centroespanol.ru/MatriculaEscuelas</loc>
</url>
<url>
  <loc>http://centroespanol.ru/img/baraka2014.pdf</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/baraka/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/laplaya/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/twoday/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/ilc/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/desilena/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/eshispania/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Escuelas/alhambra/</loc>
</url>
<url>
  <loc>http://centroespanol.ru/blog_espanol</loc>
</url>
<url>
  <loc>http://centroespanol.ru/blog_catala</loc>
</url>
<url>
  <loc>http://centroespanol.ru/blog_turism</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema8</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Slovar-v-kartinkah-shopping</loc>
</url>
<url>
  <loc>http://centroespanol.ru/menu-degustacio</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema7</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Slovar-v-kartinkah-gorod</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Slovar-v-kartinkah-produkti</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Barcelona_Miro</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Mezhdunarodniy-den-knigi</loc>
</url>
<url>
  <loc>http://centroespanol.ru/sevilla</loc>
</url>
<url>
  <loc>http://centroespanol.ru/catalunya</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Arhitektura_Gaudi</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Cadaques</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Frazeologizmi_v_ismanskom</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Noviy-god-barcelona</loc>
</url>
<url>
  <loc>http://centroespanol.ru/5-faktov-ob-ispanskom-yazike</loc>
</url>
<url>
  <loc>http://centroespanol.ru/oshibki</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Download</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Meropriyatia</loc>
</url>
<url>
  <loc>http://centroespanol.ru/ispanskij-dlya-detej-i-shkolnikov</loc>
</url>
<url>
  <loc>http://centroespanol.ru/cinecurs</loc>
</url>
<url>
  <loc>http://centroespanol.ru/vecherinka25-04-14</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Kultura-katalonii</loc>
</url>
<url>
  <loc>http://centroespanol.ru/dia-de-los-muertos</loc>
</url>
<url>
  <loc>http://centroespanol.ru/konkurs</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Literatura</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Pressa</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema2</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema3</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema4</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema5</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Ispanskiy-v-dialodah-tema6</loc>
</url>
<url>
  <loc>http://centroespanol.ru/download</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Slovar-v-kartinkah-produkti-katalonskiy</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Sevilla</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Catalunya</loc>
</url>
<url>
  <loc>http://centroespanol.ru/ria</loc>
</url>
<url>
  <loc>http://centroespanol.ru/bg</loc>
</url>
<url>
  <loc>http://centroespanol.ru/uralistica</loc>
</url>
<url>
  <loc>http://centroespanol.ru/online</loc>
</url>
<url>
  <loc>http://centroespanol.ru/img/A1_programma.pdf</loc>
</url>
<url>
  <loc>http://centroespanol.ru/catala-cat</loc>
</url>
<url>
  <loc>http://centroespanol.ru/Barcelona_miro</loc>
</url>
<url>
  <loc>http://centroespanol.ru/cinehorario</loc>
</url>
<url>
  <loc>http://centroespanol.ru/img/Funes-el-memorioso.pdf</loc>
</url>
<url>
  <loc>http://centroespanol.ru/img/La-soledad-de-America-latina.pdf</loc>
</url>
</urlset>

**Comment by InnaStarchenkova** [comment]
Преподаватели
 - имя
 - фото
 - описание
Курсы
 - название (+на испанском)
 - краткое описание
 - полное описание (+ на испанском)
 - продолжительность
 - ссылка на pdf программы курса
Картинки
  - картинка
Курсы-Картинка
 - курс Id
 - картинка Id
 - это главная 
Группы 
 - курс Id
 - дата старта
 - идет ли набор
 - текстовое описание дни недели (ex: будни до 18)
 - мин кол-во людей в группе
 - макс кол-во людей в группе 
Цены на группу
 - группа Id
 - период для оплаты Id
 - цена
 - валюта
 - скидка (%)
Периоды для оплаты  курсов [весь курс, половина курса, месяц, неделя, 2 недели, 3 недели, ак. час, 1 - 3 недели, 4-8 недели]
Группа-Дни недели
  - группа Id
  - день недели
  - время начала урока
  - время конца урока
Школы (в Испании)
 - название
 - краткое описание
 - описание
 - картинки
 - адрес
 - регион Id
Школа-Тип курса [Интенсив, Полуинтенсив, Курсы для детей]
Школа-Спецкурсы [Фламенко, Кулинарный курс, История и культура Испании, Подготовка к DELE, Испанский для бизнеса]
Школа-Тип отдыха [Горы, Город, Море и пляж]
Школа- Тип проживания  [Отель, В семье, Резиденция школы, Студенческое общежитие, Апартаменты]
Школа-Картинки

Обучение в школе
 - школа Id
 - школа-тип курса Id
 - школа-тип отдыха Id
 - школа-тип проживания Id
 - школа-спецкурс  Id
 - отдельная ли комната
 - с питанием или без
 - цена
 - валюта

Спецкурсы
 - название
 - описание 

Пользователь
 - имя
 - емаил
 - сообщение
 - телефон

Мероприятия
 - название
 - дата начала
 - дата окончания
 - краткое описание
 - полное описание
Мероприятия-Картинки
 - мероприятие Id
 - картинка Id
 - главная
Пресса
 - название
 - дата
 - источник
 - картинка
 - краткое описание
 - ссылка на блог

Встречи разговорного клуба
 - название
 - дата, время
 - преподаватель
 - описание
 - уровень языка
Уровни испаского языка
 - название (+ на испанском)
 - описание
